idf_component_register(
    SRCS
        "main.c"
        "core/app_common.c"
        "core/app_launcher.c"
        "drivers/camera/camera_driver.c"
        "drivers/display/display.c"
        "drivers/touch/touch_xpt2046.c"
        "drivers/gfx/display_gfx.c"
        "drivers/storage/sdcard.c"
        "drivers/audio/i2s_audio.c"
        "drivers/audio/i2s_mic.c"
        "services/audio_player/audio_player.c"
        "services/wifi/wifi_service.c"
        "services/web_stream/http_stream.c"
        "services/battery/battery_service.c"
        "apps/camera/app_camera.c"
        "apps/roboeyes/roboeyes_display.cpp"
        "apps/settings/app_settings.c"
        "apps/sysinfo/app_sysinfo.c"
        "apps/moods/app_moods.c"
        "apps/webstream/app_webstream.c"
        "apps/touch_test/app_touch_test.c"
        "apps/music/app_music.c"
        "apps/recorder/app_recorder.c"
        "services/wake_word/wake_word_service.c"
        "services/tts/tts_service.c"
        "services/tts/sam/reciter.c"
        "services/tts/sam/render.c"
        "services/tts/sam/sam.c"
        "services/tts/sam/debug.c"
    INCLUDE_DIRS
        "."
        "core"
        "drivers/camera"
        "drivers/display"
        "drivers/touch"
        "drivers/gfx"
        "drivers/storage"
        "drivers/audio"
        "services/audio_player"
        "services/wifi"
        "services/web_stream"
        "services/battery"
        "services/wake_word"
        "services/tts"
        "services/tts/sam"
        "apps/camera"
        "apps/roboeyes"
        "apps/settings"
        "apps/sysinfo"
        "apps/moods"
        "apps/webstream"
        "apps/touch_test"
        "apps/music"
        "apps/recorder"
    REQUIRES
        esp_wifi
        lwip
        nvs_flash
        esp_netif
        esp_http_server
        esp_http_client
        esp_timer
        esp_lcd
        esp_lcd_ili9341
        driver
        esp_driver_i2s
        esp_driver_sdspi
        esp_driver_gpio
        esp_driver_spi
        RoboEyes
        esp_system
        fatfs
        sdmmc
        vfs
        espressif__esp32-camera
        espressif__esp_jpeg
        espressif__esp-sr
        app_update
        esp_app_format
)